bolumler_listesi = [
    "Acil Yardım ve Afet Yönetimi", "Adli Bilişim Mühendisliği", "Ağız ve Diş Sağlığı", 
    "Aktüerya Bilimleri", "Antropoloji", "Arkeoloji", "Astronomi ve Uzay Bilimleri", 
    "Beslenme ve Diyetetik", "Bilgisayar Mühendisliği", "Bilgisayar Programcılığı", 
    "Bilişim Sistemleri Mühendisliği", "Bilişim Sistemleri ve Teknolojileri", 
    "Biyokimya", "Biyoloji", "Biyomedikal Mühendisliği", "Biyomühendislik", 
    "Coğrafya", "Çalışma Ekonomisi ve Endüstri İlişkileri", "Çevre Mühendisliği", 
    "Çocuk Gelişimi", "Denizcilik İşletmeleri Yönetimi", "Diş Hekimliği", 
    "Eczacılık", "Ekonometri", "Ekonomi", "Elektrik-Elektronik Mühendisliği", 
    "Elektronik ve Haberleşme Mühendisliği", "Endüstri Mühendisliği", "Endüstriyel Tasarım", 
    "Felsefe", "Finans ve Bankacılık", "Fizik", "Fizyoterapi ve Rehabilitasyon", 
    "Gemi İnşaatı ve Gemi Makineleri Mühendisliği", "Gıda Mühendisliği", "Görsel İletişim Tasarımı", 
    "Grafik Tasarımı", "Halkla İlişkiler ve Reklamcılık", "Havacılık Yönetimi", 
    "Hemşirelik", "Hukuk", "İç Mimarlık", "İç Mimarlık ve Çevre Tasarımı", 
    "İktisat", "İlahiyat", "İletişim Tasarımı ve Yönetimi", "İmalat Mühendisliği", 
    "İngiliz Dili ve Edebiyatı", "İnsan Kaynakları Yönetimi", "İnşaat Mühendisliği", 
    "İstatistik", "İş Sağlığı ve Güvenliği", "İşletme", "İşletme Mühendisliği", 
    "Kamu Yönetimi", "Kimya", "Kimya Mühendisliği", "Lojistik Yönetimi", 
    "Makine Mühendisliği", "Maliye", "Malzeme Bilimi ve Nanoteknoloji Mühendisliği", 
    "Matematik", "Matematik Mühendisliği", "Mekatronik Mühendisliği", "Metalurji ve Malzeme Mühendisliği", 
    "Mimarlık", "Moleküler Biyoloji ve Genetik", "Otomotiv Mühendisliği", 
    "Özel Eğitim Öğretmenliği", "Pazarlama", "Psikoloji", "Psikolojik Danışmanlık ve Rehberlik (PDR)", 
    "Radyo, Televizyon ve Sinema", "Sağlık Yönetimi", "Sınıf Öğretmenliği", 
    "Siyaset Bilimi ve Kamu Yönetimi", "Siyaset Bilimi ve Uluslararası İlişkiler", 
    "Sosyoloji", "Tarih", "Tekstil Mühendisliği", "Tıp", "Turizm İşletmeciliği", 
    "Türk Dili ve Edebiyatı", "Uçak Mühendisliği", "Uluslararası Ticaret ve Finansman", 
    "Uluslararası Ticaret ve Lojistik", "Veteriner", "Yapay Zeka Mühendisliği", 
    "Yapay Zeka ve Veri Mühendisliği", "Yazılım Mühendisliği", "Yeni Medya ve İletişim", 
    "Yönetim Bilişim Sistemleri (YBS)", "Ziraat Mühendisliği", 
    "Diğer (Listede Yok)"
]